version: '1'
name: Nexus
description: ''
repository:
  path: .
  git: true
panes:
  - id: pane-16
    name: opencode 一号
    agent: opencode
    restore: continue
  - id: pane-17
    name: opencode 二号
    agent: opencode
    restore: manual
  - id: pane-18
    name: opencode 三号
    agent: opencode
    restore: manual
