version: '1'
name: Nexus
description: ''
repository:
  path: .
  git: true
panes:
  - id: pane-2
    name: cc1
    agent: claudecode
    restore: continue
    isolation: shared
  - id: pane-3
    name: cc2
    agent: claudecode
    restore: manual
    isolation: shared
  - id: pane-4
    name: oc1
    agent: opencode
    restore: manual
    isolation: shared
  - id: pane-5
    name: Agent Pane 展示优化
    agent: claudecode
    restore: manual
    isolation: worktree
    worktreePath: /root/workspace/Nexus/.nexus/worktrees/pane-5
    branch: nexus/pane-5-agent-pane-展示优化
  - id: pane-6
    name: chore
    agent: opencode
    restore: manual
    isolation: shared
