version: '1'
name: Nexus
description: ''
repository:
  path: .
  git: true
panes:
  - id: pane-4
    name: '123'
    agent: opencode
    restore: continue
  - id: pane-5
    name: '12313213'
    agent: opencode
    restore: continue
