version: '1'
name: server
description: ''
repository:
  path: .
  git: false
panes:
  - id: pane-1
    name: test
    agent: opencode
    restore: continue
  - id: pane-2
    name: sdfd
    agent: opencode
    restore: continue
